### ISSUE TITLE
[FE] UH2000: fix Hover time issue

### ISSUE THREAD

**Issue by DarioMejia** [dr-von-doom/Exclusive-legacy#12]
The header contains text that appears when hovering over the subtitles, but the text, which includes hyperlinks, disappears too quickly, making it difficult for users to click on the links.

Descriptive Image:
![image](https://github.com/user-attachments/assets/4c432485-51ab-4f46-9e0f-97e31fefa615)

**Comment by Sonya-c** [comment]
@daolivaress añado a este issue un comentario. Los enlaces se ven azules/morados (estilo por defecto de los enlaces). Podrías hacer que se vean con color negro?

**Comment by Sonya-c** [comment]
Also, podrías añadir un background color on hover 

Ahora: 
![Image](https://github.com/user-attachments/assets/4d751ca7-9211-4133-9a66-be246363c0d1)

Sugerencia: 
![Image](https://github.com/user-attachments/assets/2ae8c1d4-a34f-4ce8-b71c-b12054b6b196)
